// Operator tiles for Learn mode. Mirrors the shape of complexities[] in BigOTeacher.jsx.
// `arity` controls whether the Learn detail pane shows an A row + B row (binary),
// A row only (unary), or A row + shift-amount slider (shift).

export const operators = [
  {
    id: "repr",
    symbol: "0b",
    name: "Representation",
    label: "How numbers become bits",
    arity: "intro",
    color: "#a8a29e",
    accent: "#e7e5e4",
    jsExpr: "(170).toString(2).padStart(8, '0')",
    description:
      "Before any operator, agree on how an integer becomes a bit pattern. JavaScript coerces operands to 32-bit signed integers for all bitwise ops (except BigInt). The high bit is the sign.",
    code: [
      { line: "// 170 in three bases, same number", highlight: false },
      { line: "0xAA           // hex", highlight: true, note: "Each hex digit = 4 bits." },
      { line: "0b10101010     // binary", highlight: true, note: "Literal bit pattern." },
      { line: "170            // decimal", highlight: false },
      { line: "", highlight: false },
      { line: "// JS coerces to 32-bit signed before &|^~<<>>", highlight: false },
      { line: "(3.7 | 0)      // 3 — truncate toward zero", highlight: true, note: "Useful floor-for-positive-numbers idiom." },
      { line: "(2**32)        // 4294967296", highlight: false },
      { line: "(2**32) | 0    // 0 — overflowed past 32 bits", highlight: true, note: "Bits past 31 disappear." },
    ],
    explanation:
      "Everything in this app assumes you're reading bits MSB-first in a fixed width (usually 8). If a result looks surprising (like ~0 === -1), it's almost always the 32-bit signed coercion talking.",
    gotcha: "All bitwise operators except BigInt variants silently convert to Int32.",
  },
  {
    id: "and",
    symbol: "&",
    name: "AND",
    label: "Keep bits that are 1 in both",
    arity: "binary",
    color: "#f59e0b",
    accent: "#fbbf24",
    jsExpr: "a & b",
    description:
      "Result bit is 1 only when both input bits are 1. The classic use: a mask that keeps only the bits you care about.",
    code: [
      { line: "const byte = 0b11011010;", highlight: false },
      { line: "const lowNibble = byte & 0x0F;", highlight: true, note: "Keep low 4 bits — zero everything else." },
      { line: "// lowNibble === 0b1010 === 10", highlight: false },
      { line: "", highlight: false },
      { line: "// Test if bit 3 is set:", highlight: false },
      { line: "const bit3 = (byte & (1 << 3)) !== 0;", highlight: true, note: "Make a one-hot mask, AND it in, check nonzero." },
    ],
    explanation:
      "AND is your extractor. Want the low byte of an int? & 0xFF. Want to isolate a single bit? & (1 << k). Want to check if something is even? & 1 and compare to 0.",
    gotcha: "AND with 0 is always 0 — it's often the cheap way to force a clear.",
  },
  {
    id: "or",
    symbol: "|",
    name: "OR",
    label: "Set bits that are 1 in either",
    arity: "binary",
    color: "#f59e0b",
    accent: "#fbbf24",
    jsExpr: "a | b",
    description:
      "Result bit is 1 when either input bit is 1. The classic use: combining flags.",
    code: [
      { line: "const READ  = 1 << 0;  // 0b001", highlight: false },
      { line: "const WRITE = 1 << 1;  // 0b010", highlight: false },
      { line: "const EXEC  = 1 << 2;  // 0b100", highlight: false },
      { line: "", highlight: false },
      { line: "const perms = READ | WRITE;", highlight: true, note: "Combine flags into a single integer." },
      { line: "// perms === 0b011 === 3", highlight: false },
      { line: "", highlight: false },
      { line: "// Add EXEC later without losing existing flags:", highlight: false },
      { line: "const full = perms | EXEC;   // 0b111", highlight: true, note: "OR is idempotent — adding a flag already present changes nothing." },
    ],
    explanation:
      "OR is your combiner. Stacking permission flags, merging bitmaps, setting a specific bit without clobbering the others.",
    gotcha: "(n | 0) is the 32-bit truncation idiom — it zeros nothing but coerces to Int32.",
  },
  {
    id: "xor",
    symbol: "^",
    name: "XOR",
    label: "Flip bits that differ",
    arity: "binary",
    color: "#f59e0b",
    accent: "#fbbf24",
    jsExpr: "a ^ b",
    description:
      "Result bit is 1 when input bits differ. XOR is its own inverse: (a ^ b) ^ b === a. It's also polynomial addition in GF(2) — more on that in the Polynomial mode.",
    code: [
      { line: "// Toggle bit 2:", highlight: false },
      { line: "let flags = 0b0101;", highlight: false },
      { line: "flags = flags ^ (1 << 2);", highlight: true, note: "XOR with a one-hot mask flips that bit." },
      { line: "// flags === 0b0001", highlight: false },
      { line: "", highlight: false },
      { line: "// Swap without a temp:", highlight: false },
      { line: "let a = 5, b = 9;", highlight: false },
      { line: "a ^= b; b ^= a; a ^= b;", highlight: true, note: "Three XORs, no intermediate. a and b are swapped." },
    ],
    explanation:
      "XOR differs from OR only at the 'both are 1' position: OR keeps it 1, XOR zeros it. That's the entire story — and it's why XOR-ing the same value twice returns to the start.",
    gotcha: "a ^ a === 0 for any int a. Handy for building identities and parity checks.",
  },
  {
    id: "not",
    symbol: "~",
    name: "NOT",
    label: "Flip every bit",
    arity: "unary",
    color: "#f59e0b",
    accent: "#fbbf24",
    jsExpr: "~n",
    description:
      "Every 0 becomes 1, every 1 becomes 0. Because JS bitwise runs on 32-bit signed ints, ~0 is -1 and ~5 is -6. Mask to see a clean unsigned view.",
    code: [
      { line: "~0       // -1 — all 32 bits flipped", highlight: true, note: "Two's complement: ~n === -(n + 1)." },
      { line: "~5       // -6", highlight: false },
      { line: "~5 & 0xFF    // 250 — low-byte view", highlight: true, note: "Masking reveals the bit pattern without sign extension." },
      { line: "", highlight: false },
      { line: "// Clear bit k:", highlight: false },
      { line: "const cleared = n & ~(1 << k);", highlight: true, note: "Invert a one-hot mask to get an all-but-k mask." },
    ],
    explanation:
      "The two classic uses: 'invert this mask' (then AND it in to clear bits) and the identity ~n === -(n + 1), which falls out of two's complement.",
    gotcha: "~n on an 8-bit number is a 32-bit result. Mask with & 0xFF to clip back to 8 bits.",
  },
  {
    id: "shl",
    symbol: "<<",
    name: "Shift left",
    label: "Multiply by powers of 2",
    arity: "shift",
    color: "#f59e0b",
    accent: "#fbbf24",
    jsExpr: "n << k",
    description:
      "Move all bits left by k positions. Zeros fill from the right. Bits that shift past the 32nd position are dropped.",
    code: [
      { line: "1 << 0    // 1", highlight: false },
      { line: "1 << 3    // 8 — same as 2 ** 3", highlight: true, note: "<< k is multiplication by 2^k." },
      { line: "1 << 31   // -2147483648", highlight: true, note: "Overflows into the sign bit — 32-bit signed coercion at work." },
      { line: "1 << 32   // 1 — JS takes shift amount mod 32", highlight: true, note: "Not a compile error, not zero. Just mod 32." },
      { line: "", highlight: false },
      { line: "// Build a one-hot mask for bit k:", highlight: false },
      { line: "const maskK = 1 << k;", highlight: true, note: "The universal 'touch bit k' constructor." },
    ],
    explanation:
      "Shift left by k is the same as multiplying by 2^k, up until bits spill off the top. And in polynomial land, it's multiplication by x^k.",
    gotcha: "The shift amount is taken mod 32 in JS — 1 << 32 is 1, not 0.",
  },
  {
    id: "shr",
    symbol: ">>",
    name: "Arithmetic shift right",
    label: "Divide by powers of 2, keep sign",
    arity: "shift",
    color: "#f59e0b",
    accent: "#fbbf24",
    jsExpr: "n >> k",
    description:
      "Move all bits right by k. The sign bit is extended — negative numbers stay negative. This is 'signed' or 'arithmetic' right shift.",
    code: [
      { line: "8 >> 2    // 2", highlight: false },
      { line: "(-8) >> 2 // -2 — sign bit preserved", highlight: true, note: "Each shift fills from the left with the sign bit." },
      { line: "(-1) >> 1 // -1 — all-ones forever", highlight: true, note: "Sign-extension keeps -1 as -1 no matter how many shifts." },
      { line: "", highlight: false },
      { line: "// Integer division by 2 (for non-negative ints):", highlight: false },
      { line: "const half = n >> 1;", highlight: true, note: "Safe for n ≥ 0. For negative n this rounds toward -∞, not 0." },
    ],
    explanation:
      "Prefer >> when you're dividing a potentially-negative integer by a power of two and want to preserve sign. Prefer >>> when you want the raw bits without sign extension.",
    gotcha: "(-1) >> 1 is -1, not 2147483647. Use >>> for the unsigned view.",
  },
  {
    id: "ushr",
    symbol: ">>>",
    name: "Unsigned shift right",
    label: "Divide by powers of 2, fill with zero",
    arity: "shift",
    color: "#f59e0b",
    accent: "#fbbf24",
    jsExpr: "n >>> k",
    description:
      "Move all bits right by k. Zeros fill from the left regardless of the sign bit. Also the cheap way to coerce a negative number to its unsigned 32-bit view.",
    code: [
      { line: "8 >>> 2   // 2", highlight: false },
      { line: "(-1) >>> 0  // 4294967295", highlight: true, note: "Canonical 'show me the unsigned bits' trick." },
      { line: "(-8) >>> 2  // 1073741822 — unsigned interpretation", highlight: true, note: "Sign bit becomes just another 1." },
      { line: "", highlight: false },
      { line: "// Halve without worrying about sign:", highlight: false },
      { line: "const mid = (lo + hi) >>> 1;", highlight: true, note: "Prevents overflow-to-negative in binary search on 32-bit ints." },
    ],
    explanation:
      ">>> is JS's only unsigned operator. It's useful in two places: binary-search midpoints (avoids overflow-to-negative) and 'show me what the bits really look like' debugging.",
    gotcha: "The result of n >>> 0 is always non-negative, even if n was negative.",
  },
];
