// ============================================================
// OPTIMIZATION CHALLENGES
// Each challenge pairs a naive O(n²) (or worse) solution with an
// O(n) version that uses a hash structure, frequency counter,
// prefix scan, or array buffering.
//
// Shape:
//   { id, title, prompt, tier,
//     slow:  { complexity, code[], note },
//     fast:  { complexity, code[], note },
//     options: [{ key, label, correct, hint? }],
//     insight }
// ============================================================
export const optimizations = [
  {
    id: "contains-duplicate",
    title: "Contains Duplicate",
    prompt: "Does the array contain any repeated value?",
    tier: 1,
    slow: {
      complexity: "O(n\u00b2)",
      code: [
        "function hasDup(arr) {",
        "  for (let i = 0; i < arr.length; i++) {",
        "    for (let j = i + 1; j < arr.length; j++) {",
        "      if (arr[i] === arr[j]) return true;",
        "    }",
        "  }",
        "  return false;",
        "}",
      ],
      note: "For each element we scan the rest of the array. That's ~n\u00b2/2 comparisons.",
    },
    fast: {
      complexity: "O(n)",
      code: [
        "function hasDup(arr) {",
        "  const seen = new Set();",
        "  for (const x of arr) {",
        "    if (seen.has(x)) return true;",
        "    seen.add(x);",
        "  }",
        "  return false;",
        "}",
      ],
      note: "A Set replaces the inner loop with an O(1) lookup. One pass, constant work per step.",
    },
    options: [
      { key: "set", label: "Use a Set for O(1) membership", correct: true },
      { key: "sort", label: "Sort first, then scan for adjacent dupes", correct: false,
        hint: "Works, but gives O(n log n) \u2014 a hash is strictly better here." },
      { key: "prefix", label: "Prefix sums", correct: false,
        hint: "Prefix sums solve range-sum problems, not membership." },
      { key: "none", label: "It's already optimal", correct: false,
        hint: "The inner loop is the tell \u2014 it's doing work a hash lookup could replace." },
    ],
    insight:
      "Whenever the inner loop is just 'have I seen this before?', a Set collapses it to O(1). Nested loop \u2192 single pass.",
  },

  {
    id: "two-sum-exists",
    title: "Pair With Target Sum",
    prompt: "Do any two elements sum to the target?",
    tier: 2,
    slow: {
      complexity: "O(n\u00b2)",
      code: [
        "function hasPair(arr, target) {",
        "  for (let i = 0; i < arr.length; i++) {",
        "    for (let j = i + 1; j < arr.length; j++) {",
        "      if (arr[i] + arr[j] === target) return true;",
        "    }",
        "  }",
        "  return false;",
        "}",
      ],
      note: "Every pair is checked \u2014 the classic O(n\u00b2) pairwise scan.",
    },
    fast: {
      complexity: "O(n)",
      code: [
        "function hasPair(arr, target) {",
        "  const seen = new Set();",
        "  for (const x of arr) {",
        "    if (seen.has(target - x)) return true;",
        "    seen.add(x);",
        "  }",
        "  return false;",
        "}",
      ],
      note: "For each x, we look for its complement (target - x) in O(1). One pass, done.",
    },
    options: [
      { key: "set", label: "Hash the complement (target - x)", correct: true },
      { key: "sort", label: "Sort + two pointers", correct: false,
        hint: "Valid technique, but that's O(n log n). A hash nails O(n)." },
      { key: "freq", label: "Count frequencies first", correct: false,
        hint: "Close, but overkill. A single-pass Set is enough for existence." },
      { key: "none", label: "Already optimal", correct: false },
    ],
    insight:
      "'For each x, is its partner in the array?' is a hash-lookup shape. Don't re-scan \u2014 remember what you've seen.",
  },

  {
    id: "first-unique-char",
    title: "First Non-Repeating Character",
    prompt: "Return the first character in the string that appears only once.",
    tier: 2,
    slow: {
      complexity: "O(n\u00b2)",
      code: [
        "function firstUnique(str) {",
        "  for (let i = 0; i < str.length; i++) {",
        "    let count = 0;",
        "    for (let j = 0; j < str.length; j++) {",
        "      if (str[i] === str[j]) count++;",
        "    }",
        "    if (count === 1) return str[i];",
        "  }",
        "  return null;",
        "}",
      ],
      note: "For each character we re-count its occurrences across the whole string \u2014 n \u00d7 n work.",
    },
    fast: {
      complexity: "O(n)",
      code: [
        "function firstUnique(str) {",
        "  const freq = new Map();",
        "  for (const c of str) freq.set(c, (freq.get(c) ?? 0) + 1);",
        "  for (const c of str) if (freq.get(c) === 1) return c;",
        "  return null;",
        "}",
      ],
      note: "Two sequential passes: count once, then scan once. O(n) + O(n) = O(n).",
    },
    options: [
      { key: "freq", label: "Build a frequency map, then single-pass scan", correct: true },
      { key: "set", label: "Use a Set of seen characters", correct: false,
        hint: "A Set tells you 'seen vs not seen', but not 'exactly once'. You need counts." },
      { key: "sort", label: "Sort the string, then scan for singletons", correct: false,
        hint: "That loses the original order \u2014 you can't tell which was first." },
      { key: "none", label: "Already optimal", correct: false },
    ],
    insight:
      "Two sequential O(n) passes beat one nested O(n\u00b2) pass. When the inner loop is re-computing something, pre-compute it once.",
  },

  {
    id: "valid-anagram",
    title: "Valid Anagram",
    prompt: "Do the two strings use the exact same characters (same counts)?",
    tier: 3,
    slow: {
      complexity: "O(n\u00b2)",
      code: [
        "function isAnagram(a, b) {",
        "  if (a.length !== b.length) return false;",
        "  const used = new Array(b.length).fill(false);",
        "  for (const ch of a) {",
        "    let matched = false;",
        "    for (let j = 0; j < b.length; j++) {",
        "      if (!used[j] && b[j] === ch) {",
        "        used[j] = true; matched = true; break;",
        "      }",
        "    }",
        "    if (!matched) return false;",
        "  }",
        "  return true;",
        "}",
      ],
      note: "For each char in a, we scan b to find an unused match. Pairwise \u2014 O(n\u00b2).",
    },
    fast: {
      complexity: "O(n)",
      code: [
        "function isAnagram(a, b) {",
        "  if (a.length !== b.length) return false;",
        "  const count = new Map();",
        "  for (const c of a) count.set(c, (count.get(c) ?? 0) + 1);",
        "  for (const c of b) {",
        "    const n = count.get(c);",
        "    if (!n) return false;",
        "    count.set(c, n - 1);",
        "  }",
        "  return true;",
        "}",
      ],
      note: "Count characters in a, then decrement as we walk b. If any count goes negative, mismatch.",
    },
    options: [
      { key: "freq", label: "Frequency counter (Map)", correct: true },
      { key: "sort", label: "Sort both and compare", correct: false,
        hint: "Works, but that's O(n log n). A frequency map is strictly O(n)." },
      { key: "set", label: "Compare as Sets", correct: false,
        hint: "Sets throw away duplicates \u2014 'aab' and 'abb' would look equal." },
      { key: "none", label: "Already optimal", correct: false },
    ],
    insight:
      "Anagrams are a character-count identity. Count, then walk \u2014 no pairwise matching needed.",
  },

  {
    id: "intersection",
    title: "Array Intersection",
    prompt: "Return the unique values that appear in both arrays.",
    tier: 3,
    slow: {
      complexity: "O(n\u00b2)",
      code: [
        "function intersect(a, b) {",
        "  const out = [];",
        "  for (const x of a) {",
        "    if (b.includes(x) && !out.includes(x)) {",
        "      out.push(x);",
        "    }",
        "  }",
        "  return out;",
        "}",
      ],
      note: "`b.includes` and `out.includes` each scan linearly inside the outer loop \u2014 O(n\u00b2).",
    },
    fast: {
      complexity: "O(n)",
      code: [
        "function intersect(a, b) {",
        "  const setB = new Set(b);",
        "  const seen = new Set();",
        "  const out = [];",
        "  for (const x of a) {",
        "    if (setB.has(x) && !seen.has(x)) {",
        "      out.push(x);",
        "      seen.add(x);",
        "    }",
        "  }",
        "  return out;",
        "}",
      ],
      note: "Turn `b` into a Set once. Then each membership check is O(1). Single pass over a.",
    },
    options: [
      { key: "set", label: "Convert b to a Set for O(1) lookups", correct: true },
      { key: "sort", label: "Sort both + merge-style scan", correct: false,
        hint: "Works, but costs O(n log n). Hash is strictly better when order doesn't matter." },
      { key: "prefix", label: "Prefix sums", correct: false,
        hint: "Prefix sums are for range aggregates, not membership." },
      { key: "none", label: "Already optimal", correct: false,
        hint: "The hidden loop is inside `.includes` \u2014 it's O(n) per call." },
    ],
    insight:
      "`Array.includes` inside a loop is a red flag. Promote one side to a Set and the outer loop collapses to O(n).",
  },

  {
    id: "string-build-loop",
    title: "Build a String in a Loop",
    prompt: "Concatenate an array of n single-character strings into one string.",
    tier: 4,
    slow: {
      complexity: "O(n\u00b2)",
      code: [
        "function build(parts) {",
        "  let out = '';",
        "  for (let i = 0; i < parts.length; i++) {",
        "    out += parts[i];",
        "  }",
        "  return out;",
        "}",
      ],
      note: "Strings are immutable. Each `+=` copies the whole accumulator. 1 + 2 + \u2026 + n = O(n\u00b2).",
    },
    fast: {
      complexity: "O(n)",
      code: [
        "function build(parts) {",
        "  const buf = [];",
        "  for (let i = 0; i < parts.length; i++) {",
        "    buf.push(parts[i]);",
        "  }",
        "  return buf.join('');",
        "}",
      ],
      note: "Push is amortized O(1), and `.join` does one final linear pass. Total: O(n).",
    },
    options: [
      { key: "array-join", label: "Collect into an array, then .join('') at the end", correct: true },
      { key: "set", label: "Use a Set", correct: false,
        hint: "A Set removes duplicates \u2014 wrong shape for concatenation." },
      { key: "map", label: "Use a Map keyed by index", correct: false,
        hint: "Maps don't concatenate, and the real problem is the copy cost of `+=`." },
      { key: "none", label: "Already optimal", correct: false,
        hint: "The innocent `+=` hides the quadratic cost \u2014 each one copies the accumulator." },
    ],
    insight:
      "Immutable strings + loop = O(n\u00b2) disguised as a linear pass. Buffer into an array, join once.",
  },

  {
    id: "pair-target-diff",
    title: "Count Pairs With Target Difference",
    prompt: "How many ordered pairs (i, j) with i \u2260 j satisfy arr[i] - arr[j] === k?",
    tier: 4,
    slow: {
      complexity: "O(n\u00b2)",
      code: [
        "function countPairs(arr, k) {",
        "  let count = 0;",
        "  for (let i = 0; i < arr.length; i++) {",
        "    for (let j = 0; j < arr.length; j++) {",
        "      if (i !== j && arr[i] - arr[j] === k) count++;",
        "    }",
        "  }",
        "  return count;",
        "}",
      ],
      note: "Every (i, j) pair is checked \u2014 n\u00b2 comparisons even if we could have counted smarter.",
    },
    fast: {
      complexity: "O(n)",
      code: [
        "function countPairs(arr, k) {",
        "  const freq = new Map();",
        "  for (const x of arr) freq.set(x, (freq.get(x) ?? 0) + 1);",
        "  let count = 0;",
        "  for (const [x, n] of freq) {",
        "    const other = freq.get(x + k) ?? 0;",
        "    count += n * other;",
        "  }",
        "  return count;",
        "}",
      ],
      note: "For each distinct x, every occurrence of x+k pairs with it. Multiply the counts.",
    },
    options: [
      { key: "freq", label: "Frequency map + multiply counts", correct: true },
      { key: "sort", label: "Sort + binary search for x+k", correct: false,
        hint: "Gives O(n log n). A frequency map gets you to O(n)." },
      { key: "set", label: "Use a Set", correct: false,
        hint: "A Set can't count duplicates \u2014 you'd miss pairs when values repeat." },
      { key: "none", label: "Already optimal", correct: false },
    ],
    insight:
      "When counting pairs, turn 'for each pair' into 'for each value, how many partners exist?'. Multiplication replaces the inner loop.",
  },

  {
    id: "nearby-duplicate",
    title: "Duplicate Within Distance k",
    prompt: "Are there two equal values at indices no more than k apart?",
    tier: 5,
    slow: {
      complexity: "O(n\u00b7k)",
      code: [
        "function nearbyDup(arr, k) {",
        "  for (let i = 0; i < arr.length; i++) {",
        "    const end = Math.min(i + k + 1, arr.length);",
        "    for (let j = i + 1; j < end; j++) {",
        "      if (arr[i] === arr[j]) return true;",
        "    }",
        "  }",
        "  return false;",
        "}",
      ],
      note: "For each i we scan the next k elements. When k \u2248 n, this degrades to full O(n\u00b2).",
    },
    fast: {
      complexity: "O(n)",
      code: [
        "function nearbyDup(arr, k) {",
        "  const window = new Set();",
        "  for (let i = 0; i < arr.length; i++) {",
        "    if (window.has(arr[i])) return true;",
        "    window.add(arr[i]);",
        "    if (window.size > k) window.delete(arr[i - k]);",
        "  }",
        "  return false;",
        "}",
      ],
      note: "A Set holds the last k elements. Each step: one add, one has, one delete \u2014 all O(1).",
    },
    options: [
      { key: "set", label: "Sliding-window Set of size k", correct: true },
      { key: "sort", label: "Sort + compare neighbors", correct: false,
        hint: "Sorting destroys index information \u2014 you can't reconstruct the distance." },
      { key: "freq", label: "Full frequency map", correct: false,
        hint: "A full map loses the 'within k' constraint. You need a bounded window." },
      { key: "none", label: "Already optimal", correct: false },
    ],
    insight:
      "Pair constraints limited by distance call for a sliding window. A Set gives you O(1) membership inside a window of fixed size.",
  },
];
