// ============================================================
// PRACTICE QUESTIONS
// Shape: { id, tier, type, prompt, code?[], options?[], answer,
//         explanation, correctLines?[], optionA?, optionB? }
// Types: multiple_choice | true_false | identify_lines | compare
// Tiers: 1 Fundamentals | 2 Recognition | 3 Comparison | 4 Decomposition | 5 Traps & Subtlety
// correctLines is 0-indexed against the code[] array.
// ============================================================
export const questions = [
  // ---------- A. O(1) ARRAY OPS ----------
  { id: "arr-access", tier: 1, type: "multiple_choice",
    prompt: "What's the complexity of arr[1000] on a regular JavaScript array?",
    options: ["O(1)", "O(log n)", "O(n)", "Depends on array size"], answer: 0,
    explanation: "Arrays are contiguous memory — indexing is one arithmetic operation regardless of position or length." },
  { id: "arr-length", tier: 1, type: "multiple_choice",
    prompt: "What's the complexity of arr.length?",
    options: ["O(1)", "O(log n)", "O(n)", "O(n log n)"], answer: 0,
    explanation: "Length is stored as a property on the array, not counted on demand. Reading it is a single lookup." },
  { id: "arr-pop", tier: 1, type: "multiple_choice",
    prompt: "What's the complexity of arr.pop()?",
    options: ["O(1)", "O(log n)", "O(n)", "O(n²)"], answer: 0,
    explanation: "pop() removes and returns the last element. No shifting is needed — it's always constant time." },
  { id: "arr-last", tier: 2, type: "multiple_choice",
    prompt: "What's the complexity of arr[arr.length - 1]?",
    options: ["O(1)", "O(log n)", "O(n)", "Depends"], answer: 0,
    explanation: "Two O(1) operations composed: reading length, then indexing. Still constant time overall." },
  { id: "arr-swap", tier: 2, type: "multiple_choice",
    prompt: "What's the complexity of swapping two elements by index?",
    code: ["[arr[i], arr[j]] = [arr[j], arr[i]];"],
    options: ["O(1)", "O(log n)", "O(n)", "O(n²)"], answer: 0,
    explanation: "Two indexed reads and two indexed writes. All O(1). No matter how big the array, a swap is constant work." },
  { id: "arr-push-amortized", tier: 5, type: "true_false",
    prompt: "arr.push(x) is always O(1).", answer: false,
    explanation: "It's O(1) amortized, not strictly. Occasional reallocations cost O(n), but averaged over many pushes it's constant per operation. 'Amortized' is the key word." },

  // ---------- B. O(1) HASH / MAP OPS ----------
  { id: "map-get", tier: 1, type: "multiple_choice",
    prompt: "What's the average complexity of map.get(key)?",
    options: ["O(1)", "O(log n)", "O(n)", "O(n log n)"], answer: 0,
    explanation: "Hash maps jump directly to the bucket via the hash function. Average O(1), worst O(n) with pathological collisions." },
  { id: "map-set", tier: 1, type: "multiple_choice",
    prompt: "What's the average complexity of map.set(key, value)?",
    options: ["O(1)", "O(log n)", "O(n)", "O(n²)"], answer: 0,
    explanation: "Hash the key, write to the bucket. Constant time on average — the same story as lookup, just in reverse." },
  { id: "map-has", tier: 1, type: "multiple_choice",
    prompt: "What's the average complexity of map.has(key)?",
    options: ["O(1)", "O(log n)", "O(n)", "Depends on map size"], answer: 0,
    explanation: "Membership check is the same operation as a lookup — hash, probe the bucket, return. Average O(1)." },
  { id: "obj-prop", tier: 1, type: "multiple_choice",
    prompt: "What's the average complexity of obj['userId']?",
    options: ["O(1)", "O(log n)", "O(n)", "O(n²)"], answer: 0,
    explanation: "Plain JS objects are hash-backed under the hood — property access is average O(1)." },
  { id: "map-delete", tier: 2, type: "multiple_choice",
    prompt: "What's the average complexity of map.delete(key)?",
    options: ["O(1)", "O(log n)", "O(n)", "O(n log n)"], answer: 0,
    explanation: "Find the bucket via hash, remove the entry. Constant on average — same cost class as get/set." },
  { id: "map-vs-obj-lookup", tier: 3, type: "multiple_choice",
    prompt: "For a single key lookup, which is asymptotically faster: Map.get or obj[key]?",
    options: ["Map.get", "obj[key]", "Neither — both are O(1) on average", "Depends on key type"], answer: 2,
    explanation: "Both are hash-backed and average O(1). Micro-benchmarks may differ, but Big O treats them the same. Map has predictable key types; objects can be faster for short-lived lookups — but neither is asymptotically better." },
  { id: "map-worst-case", tier: 3, type: "true_false",
    prompt: "Hash map lookups are always O(1).", answer: false,
    explanation: "Average case is O(1), but the worst case degrades to O(n) when many keys collide in the same bucket. Adversarial inputs or a bad hash function can trigger this." },

  // ---------- C. O(1) SET OPS ----------
  { id: "set-has", tier: 1, type: "multiple_choice",
    prompt: "What's the average complexity of set.has(x)?",
    options: ["O(1)", "O(log n)", "O(n)", "O(n²)"], answer: 0,
    explanation: "Sets are hash-backed — membership is average O(1) regardless of set size." },
  { id: "set-add", tier: 1, type: "multiple_choice",
    prompt: "What's the average complexity of set.add(x)?",
    options: ["O(1)", "O(log n)", "O(n)", "Depends"], answer: 0,
    explanation: "Hash x, drop it in the bucket. Constant on average — same shape as map.set." },
  { id: "set-delete", tier: 2, type: "multiple_choice",
    prompt: "What's the average complexity of set.delete(x)?",
    options: ["O(1)", "O(log n)", "O(n)", "O(n log n)"], answer: 0,
    explanation: "Hash, locate bucket, remove. Average constant time — same story as get, set, has." },
  { id: "set-dedupe", tier: 2, type: "multiple_choice",
    prompt: "What's the total complexity of deduplicating an array using a Set?",
    code: ["const unique = [...new Set(arr)];"],
    options: ["O(1)", "O(log n)", "O(n)", "O(n²)"], answer: 2,
    explanation: "Each set.add is O(1), but we call it n times — the total cost is O(n). The alternative (nested loop with .includes) would be O(n²)." },

  // ---------- D. O(1) STRING OPS ----------
  { id: "str-length", tier: 1, type: "multiple_choice",
    prompt: "What's the complexity of str.length?",
    options: ["O(1)", "O(log n)", "O(n)", "Depends on string length"], answer: 0,
    explanation: "String length is stored as a property — reading it is a single lookup." },
  { id: "str-char-at", tier: 1, type: "multiple_choice",
    prompt: "What's the complexity of str.charAt(i) or str[i]?",
    options: ["O(1)", "O(log n)", "O(n)", "O(n log n)"], answer: 0,
    explanation: "Strings are stored as indexed sequences — reading a single code unit at position i is constant time." },
  { id: "str-char-code-at", tier: 1, type: "multiple_choice",
    prompt: "What's the complexity of str.charCodeAt(i)?",
    options: ["O(1)", "O(log n)", "O(n)", "Depends on the character"], answer: 0,
    explanation: "Same cost class as charAt — one indexed read, then a type coercion. Constant time." },
  { id: "str-concat-loop", tier: 5, type: "multiple_choice",
    prompt: "What's the total complexity of building a string via += inside a loop over n chars?",
    code: ["let out = '';", "for (let i = 0; i < arr.length; i++) {", "  out += arr[i];", "}"],
    options: ["O(n)", "O(n log n)", "O(n²)", "O(1)"], answer: 2,
    explanation: "Strings are immutable in JS. Each += creates a new string by copying all previous chars — 1 + 2 + ... + n = O(n²). Use an array and .join() for O(n)." },

  // ---------- E. LINEAR TRAVERSAL ----------
  { id: "lin-for", tier: 1, type: "multiple_choice",
    prompt: "What's the complexity of this function?",
    code: ["function print(arr) {", "  for (let i = 0; i < arr.length; i++) {", "    console.log(arr[i]);", "  }", "}"],
    options: ["O(1)", "O(log n)", "O(n)", "O(n²)"], answer: 2,
    explanation: "A single loop iterates through every element exactly once. The work scales directly with input size n." },
  { id: "lin-forEach", tier: 1, type: "multiple_choice",
    prompt: "What's the complexity of arr.forEach(fn) where fn is O(1)?",
    options: ["O(1)", "O(log n)", "O(n)", "O(n²)"], answer: 2,
    explanation: "forEach visits every element once. Each visit is O(1), so total is O(n)." },
  { id: "lin-for-of", tier: 1, type: "multiple_choice",
    prompt: "What's the complexity of this loop?",
    code: ["for (const x of arr) {", "  total += x;", "}"],
    options: ["O(1)", "O(log n)", "O(n)", "O(n²)"], answer: 2,
    explanation: "for...of iterates the full iterable. For an array of length n, that's n iterations of constant work each." },
  { id: "lin-reduce", tier: 2, type: "multiple_choice",
    prompt: "What's the complexity of arr.reduce((a,b) => a+b, 0)?",
    options: ["O(1)", "O(log n)", "O(n)", "O(n²)"], answer: 2,
    explanation: "reduce visits every element exactly once, applying the (O(1)) reducer. Total: O(n)." },
  { id: "lin-filter", tier: 2, type: "multiple_choice",
    prompt: "What's the complexity of arr.filter(x => x > 0)?",
    options: ["O(1)", "O(log n)", "O(n)", "Depends on how many match"], answer: 2,
    explanation: "filter visits every element to test the predicate. O(n) regardless of how many pass — you still have to check them all." },
  { id: "lin-max", tier: 2, type: "multiple_choice",
    prompt: "What's the complexity of finding the maximum in an unsorted array?",
    options: ["O(1)", "O(log n)", "O(n)", "O(n log n)"], answer: 2,
    explanation: "You have no structure to exploit — you must look at every element at least once to be sure. That's O(n)." },
  { id: "lin-obj-keys-len", tier: 2, type: "multiple_choice",
    prompt: "What's the complexity of Object.keys(obj).length where obj has n keys?",
    options: ["O(1)", "O(log n)", "O(n)", "O(n²)"], answer: 2,
    explanation: "Object.keys walks every own-enumerable property to build the array — that's O(n). Don't let .length fool you; the work is in building the array." },
  { id: "lin-map-values", tier: 3, type: "multiple_choice",
    prompt: "What's the complexity of iterating all entries in a Map with n entries?",
    code: ["for (const [k, v] of map) {", "  handle(k, v);", "}"],
    options: ["O(1)", "O(log n)", "O(n)", "O(n log n)"], answer: 2,
    explanation: "Each individual access is O(1), but visiting all n entries is O(n) total. Iteration over any linear structure with n elements is O(n)." },

  // ---------- F. LOGARITHMIC ----------
  { id: "log-binary-search", tier: 2, type: "multiple_choice",
    prompt: "What's the complexity of binary search on a sorted array?",
    code: ["function bs(arr, t) {", "  let lo = 0, hi = arr.length - 1;", "  while (lo <= hi) {", "    const mid = (lo + hi) >> 1;", "    if (arr[mid] === t) return mid;", "    if (arr[mid] < t) lo = mid + 1;", "    else hi = mid - 1;", "  }", "}"],
    options: ["O(1)", "O(log n)", "O(n)", "O(n log n)"], answer: 1,
    explanation: "Each iteration halves the search range. Doubling the input adds just one more step — the signature of logarithmic growth." },
  { id: "log-halving", tier: 2, type: "multiple_choice",
    prompt: "What's the complexity of this function?",
    code: ["function halve(n) {", "  while (n > 1) {", "    n = n / 2;", "  }", "}"],
    options: ["O(1)", "O(log n)", "O(n)", "O(n²)"], answer: 1,
    explanation: "Each iteration halves n. Starting from n, it takes log₂(n) iterations to reach 1." },
  { id: "log-doubling", tier: 3, type: "multiple_choice",
    prompt: "What's the complexity of this loop?",
    code: ["for (let i = 1; i <= n; i *= 2) {", "  console.log(i);", "}"],
    options: ["O(1)", "O(log n)", "O(n)", "O(n log n)"], answer: 1,
    explanation: "Doubling i takes log₂(n) iterations to reach n. Same shape as halving — just run in reverse." },
  { id: "log-tripling", tier: 3, type: "multiple_choice",
    prompt: "What's the complexity of this loop?",
    code: ["for (let i = 1; i <= n; i *= 3) {", "  console.log(i);", "}"],
    options: ["O(1)", "O(log n)", "O(n)", "O(n log n)"], answer: 1,
    explanation: "log₃(n) iterations — still logarithmic. Big O doesn't care about the log base since all log bases differ by a constant factor." },
  { id: "log-bst-search", tier: 2, type: "multiple_choice",
    prompt: "What's the average complexity of search in a balanced BST with n nodes?",
    options: ["O(1)", "O(log n)", "O(n)", "O(n log n)"], answer: 1,
    explanation: "A balanced BST has depth log n. At each node you go left or right — discarding half the remaining subtree." },
  { id: "log-base-irrelevance", tier: 4, type: "true_false",
    prompt: "O(log₂ n) and O(log₁₀ n) are different complexity classes.", answer: false,
    explanation: "All logarithm bases differ only by a constant factor (log_a n = log_b n / log_b a). Big O drops constants, so they're the same class — just 'O(log n)'." },

  // ---------- G. NESTED INDEPENDENT BOUNDS ----------
  { id: "nest-square", tier: 2, type: "multiple_choice",
    prompt: "What's the complexity of this nested loop?",
    code: ["for (let i = 0; i < arr.length; i++) {", "  for (let j = 0; j < arr.length; j++) {", "    console.log(arr[i], arr[j]);", "  }", "}"],
    options: ["O(n)", "O(n log n)", "O(n²)", "O(2ⁿ)"], answer: 2,
    explanation: "Two loops, each going from 0 to n, nested. The inner body runs n × n = n² times." },
  { id: "nest-cube", tier: 3, type: "multiple_choice",
    prompt: "What's the complexity of this triple-nested loop?",
    code: ["for (let i = 0; i < n; i++) {", "  for (let j = 0; j < n; j++) {", "    for (let k = 0; k < n; k++) {", "      doWork();", "    }", "  }", "}"],
    options: ["O(n)", "O(n²)", "O(n³)", "O(3ⁿ)"], answer: 2,
    explanation: "Three loops of size n, nested. Work multiplies: n × n × n = n³." },
  { id: "nest-two-inputs", tier: 3, type: "multiple_choice",
    prompt: "Complexity when arr.length = n and other.length = m?",
    code: ["for (let i = 0; i < arr.length; i++) {", "  for (let j = 0; j < other.length; j++) {", "    console.log(arr[i], other[j]);", "  }", "}"],
    options: ["O(n)", "O(n²)", "O(nm)", "O(n + m)"], answer: 2,
    explanation: "Two independent sizes — you can't collapse them. O(nm) is the honest answer. Only if you know m = n does it become O(n²)." },
  { id: "nest-inner-const", tier: 2, type: "multiple_choice",
    prompt: "The inner loop doesn't depend on n. Complexity?",
    code: ["for (let i = 0; i < arr.length; i++) {", "  for (let j = 0; j < 100; j++) {", "    arr[i] *= 2;", "  }", "}"],
    options: ["O(1)", "O(n)", "O(n²)", "O(100n)"], answer: 1,
    explanation: "The inner loop runs a fixed 100 times regardless of n — that's a constant. Outer is n. Total: 100n → O(n)." },
  { id: "nest-string-chars", tier: 3, type: "multiple_choice",
    prompt: "What's the complexity of comparing every char to every other char? (n = str.length)",
    code: ["for (let i = 0; i < str.length; i++) {", "  for (let j = 0; j < str.length; j++) {", "    if (str[i] === str[j]) count++;", "  }", "}"],
    options: ["O(n)", "O(n log n)", "O(n²)", "O(n³)"], answer: 2,
    explanation: "Two nested loops over the string's n chars. O(n²) total work." },

  // ---------- H. NESTED DEPENDENT BOUNDS ----------
  { id: "tri-triangular", tier: 5, type: "multiple_choice",
    prompt: "The inner loop depends on i. What's the true complexity?",
    code: ["for (let i = 0; i < arr.length; i++) {", "  for (let j = 0; j < i; j++) {", "    console.log(arr[i], arr[j]);", "  }", "}"],
    options: ["O(n)", "O(n log n)", "O(n²)", "O(n²/2)"], answer: 2,
    explanation: "Total work is 0+1+2+...+(n-1) = n(n-1)/2 operations. That's still O(n²) — Big O ignores the constant factor of 1/2." },
  { id: "tri-half-inner", tier: 3, type: "multiple_choice",
    prompt: "The inner loop runs n/2 times each outer iteration. Complexity?",
    code: ["for (let i = 0; i < n; i++) {", "  for (let j = 0; j < n / 2; j++) {", "    doWork();", "  }", "}"],
    options: ["O(n)", "O(n log n)", "O(n²)", "O(n²/2)"], answer: 2,
    explanation: "Work is n × n/2 = n²/2. Drop the constant — O(n²). 'Half of n²' is still n² in Big O." },
  { id: "tri-inner-starts-i", tier: 4, type: "multiple_choice",
    prompt: "Inner loop starts at i and goes to n. Complexity?",
    code: ["for (let i = 0; i < n; i++) {", "  for (let j = i; j < n; j++) {", "    doWork();", "  }", "}"],
    options: ["O(n)", "O(n log n)", "O(n²)", "O(2ⁿ)"], answer: 2,
    explanation: "Total work is n + (n-1) + ... + 1 = n(n+1)/2. That's O(n²) — the mirror image of the classic triangular loop." },

  // ---------- I. SEQUENTIAL vs NESTED COMPOSITION ----------
  { id: "seq-two-loops", tier: 3, type: "multiple_choice",
    prompt: "Two sequential loops — total complexity?",
    code: ["for (let i = 0; i < arr.length; i++) {", "  console.log(arr[i]);", "}",
           "for (let j = 0; j < arr.length; j++) {", "  console.log(arr[j] * 2);", "}"],
    options: ["O(1)", "O(n)", "O(2n²)", "O(n²)"], answer: 1,
    explanation: "Sequential loops ADD. O(n) + O(n) = O(2n), which simplifies to O(n). Nested loops multiply; sequential loops add." },
  { id: "seq-dominant", tier: 4, type: "multiple_choice",
    prompt: "An O(n²) block followed by an O(n) block — total complexity?",
    options: ["O(n)", "O(n²)", "O(n² + n)", "O(n³)"], answer: 1,
    explanation: "O(n²) + O(n) = O(n²). Keep the dominant term; drop the smaller one. Big O cares about growth, and n² grows faster." },
  { id: "seq-log-plus-n", tier: 4, type: "multiple_choice",
    prompt: "An O(log n) step followed by an O(n) step — total complexity?",
    options: ["O(log n)", "O(n)", "O(n log n)", "O(n + log n)"], answer: 1,
    explanation: "n dominates log n for any sizable input. Total: O(n)." },
  { id: "seq-n-plus-nlogn", tier: 4, type: "multiple_choice",
    prompt: "An O(n) step followed by an O(n log n) step — total complexity?",
    options: ["O(n)", "O(n log n)", "O(n²)", "O(n + n log n)"], answer: 1,
    explanation: "n log n dominates n. Total: O(n log n). (Think: sorting dominates a single pass.)" },

  // ---------- J. RECURSION ----------
  { id: "rec-linear", tier: 3, type: "multiple_choice",
    prompt: "What's the complexity of this recursion?",
    code: ["function countdown(n) {", "  if (n <= 0) return;", "  countdown(n - 1);", "}"],
    options: ["O(1)", "O(log n)", "O(n)", "O(2ⁿ)"], answer: 2,
    explanation: "One call per decrement of n. Total: n calls, each doing O(1) work. O(n)." },
  { id: "rec-halving", tier: 3, type: "multiple_choice",
    prompt: "What's the complexity of this recursion?",
    code: ["function f(n) {", "  if (n <= 1) return;", "  f(Math.floor(n / 2));", "}"],
    options: ["O(1)", "O(log n)", "O(n)", "O(n log n)"], answer: 1,
    explanation: "Each call halves n — log n calls total, each doing O(1) work beyond the recursion." },
  { id: "rec-double", tier: 4, type: "multiple_choice",
    prompt: "Two recursive calls per step, each decrementing by 1. Complexity?",
    code: ["function f(n) {", "  if (n <= 0) return;", "  f(n - 1);", "  f(n - 1);", "}"],
    options: ["O(n)", "O(n log n)", "O(n²)", "O(2ⁿ)"], answer: 3,
    explanation: "The call tree doubles at each level, with n levels deep. 2ⁿ leaves → O(2ⁿ)." },
  { id: "rec-fib-naive", tier: 4, type: "multiple_choice",
    prompt: "What's the complexity of naive recursive Fibonacci?",
    code: ["function fib(n) {", "  if (n <= 1) return n;", "  return fib(n - 1) + fib(n - 2);", "}"],
    options: ["O(n)", "O(n log n)", "O(n²)", "O(2ⁿ)"], answer: 3,
    explanation: "Each call spawns two more, with no memoization. The call tree has roughly 2ⁿ nodes — exponential. Memoization drops it to O(n)." },
  { id: "rec-fib-memo", tier: 5, type: "multiple_choice",
    prompt: "Same Fibonacci, but with memoization. Complexity?",
    options: ["O(log n)", "O(n)", "O(n log n)", "O(2ⁿ)"], answer: 1,
    explanation: "Memoization computes each fib(k) exactly once, from fib(0) to fib(n). That's n unique subproblems — O(n) time, O(n) space." },
  { id: "rec-mergesort", tier: 4, type: "multiple_choice",
    prompt: "What's the complexity of merge sort?",
    options: ["O(n)", "O(n log n)", "O(n²)", "O(2ⁿ)"], answer: 1,
    explanation: "Divide and conquer: log n levels of recursion, each doing O(n) merging work. log n × n = O(n log n)." },

  // ---------- K. SORTING ----------
  { id: "sort-bubble", tier: 2, type: "multiple_choice",
    prompt: "What's the complexity of bubble sort (worst case)?",
    options: ["O(n)", "O(n log n)", "O(n²)", "O(n³)"], answer: 2,
    explanation: "Two nested passes over the array, swapping adjacent elements. Classic O(n²) behavior." },
  { id: "sort-merge", tier: 2, type: "multiple_choice",
    prompt: "What's the complexity of merge sort (worst case)?",
    options: ["O(n)", "O(n log n)", "O(n²)", "O(log n)"], answer: 1,
    explanation: "Split in half log n times, merge in O(n) per level. O(n log n) in every case — best, average, worst." },
  { id: "sort-builtin", tier: 3, type: "multiple_choice",
    prompt: "What's the complexity of arr.sort() on a modern JS engine?",
    options: ["O(n)", "O(n log n)", "O(n²)", "O(log n)"], answer: 1,
    explanation: "Modern engines use Timsort (or a variant) — O(n log n) in the average and worst case, sometimes O(n) on already-sorted input." },
  { id: "sort-counting", tier: 3, type: "true_false",
    prompt: "For integers in a small fixed range, counting sort can beat O(n log n).", answer: true,
    explanation: "Counting sort is O(n + k) where k is the range of values. For small k, it's effectively O(n) — faster than any comparison-based sort. The O(n log n) bound only applies to comparison sorts." },

  // ---------- L. AMORTIZED & HIDDEN COSTS ----------
  { id: "amort-unshift", tier: 5, type: "true_false",
    prompt: "arr.unshift(x) is O(1) because it just adds one element.", answer: false,
    explanation: "unshift inserts at the front, which means every existing element must shift down one index. It's O(n)." },
  { id: "amort-shift", tier: 4, type: "multiple_choice",
    prompt: "What's the complexity of arr.shift()?",
    options: ["O(1)", "O(log n)", "O(n)", "O(n²)"], answer: 2,
    explanation: "shift removes the first element — every other element must shift up one index. It's O(n), not O(1). Use a queue structure if you need fast front-removal." },
  { id: "amort-includes", tier: 4, type: "multiple_choice",
    prompt: "What's the complexity of arr.includes(x)?",
    options: ["O(1)", "O(log n)", "O(n)", "O(n log n)"], answer: 2,
    explanation: "includes scans from the start until it finds x or reaches the end. Worst case is O(n). Use a Set if you need O(1) membership." },
  { id: "amort-splice", tier: 5, type: "multiple_choice",
    prompt: "What's the complexity of arr.splice(i, 1)?",
    options: ["O(1)", "O(log n)", "O(n)", "O(n²)"], answer: 2,
    explanation: "splice removes at position i, then shifts all subsequent elements down. Worst case (removing near the start) is O(n)." },

  // ---------- M. IDENTIFY-LINES DRILLS ----------
  { id: "il-binary-search", tier: 2, type: "identify_lines",
    prompt: "Which line(s) are responsible for making this O(log n)? Click all that apply.",
    code: ["function binarySearch(arr, target) {", "  let lo = 0, hi = arr.length - 1;", "  while (lo <= hi) {", "    const mid = (lo + hi) >> 1;", "    if (arr[mid] === target) return mid;", "    if (arr[mid] < target) lo = mid + 1;", "    else hi = mid - 1;", "  }", "  return -1;", "}"],
    correctLines: [5, 6],
    explanation: "The two branches that move lo or hi past mid each discard half of the remaining range. That halving is the defining characteristic of logarithmic time." },
  { id: "il-nested-loop", tier: 2, type: "identify_lines",
    prompt: "Which line(s) drive the O(n²) behavior? Click all that apply.",
    code: ["function pairs(arr) {", "  for (let i = 0; i < arr.length; i++) {", "    for (let j = 0; j < arr.length; j++) {", "      console.log(arr[i], arr[j]);", "    }", "  }", "}"],
    correctLines: [1, 2],
    explanation: "The two nested for-loops are what create n² behavior. The console.log line is only O(1); it's the loops that multiply the work." },
  { id: "il-bubble-sort", tier: 4, type: "identify_lines",
    prompt: "Which line(s) drive the O(n²) complexity? Click all that apply.",
    code: ["function bubbleSort(arr) {", "  const n = arr.length;", "  for (let i = 0; i < n; i++) {", "    for (let j = 0; j < n - i - 1; j++) {", "      if (arr[j] > arr[j + 1]) {", "        [arr[j], arr[j + 1]] = [arr[j + 1], arr[j]];", "      }", "    }", "  }", "  return arr;", "}"],
    correctLines: [2, 3],
    explanation: "The two nested for-loops create the n² behavior. The outer loop runs n times, and the inner loop runs up to n times for each outer iteration. The swap itself is O(1)." },
  { id: "il-includes-in-loop", tier: 4, type: "identify_lines",
    prompt: "Which line(s) push this to O(n²)? Click all that apply.",
    code: ["function dedupe(arr) {", "  const out = [];", "  for (let i = 0; i < arr.length; i++) {", "    if (!out.includes(arr[i])) {", "      out.push(arr[i]);", "    }", "  }", "  return out;", "}"],
    correctLines: [2, 3],
    explanation: "The for-loop is O(n) and .includes scans up to n elements each time — their combination makes this O(n²). A Set would take it to O(n)." },
  { id: "il-recursion-doubles", tier: 5, type: "identify_lines",
    prompt: "Which line(s) make this O(2ⁿ)? Click all that apply.",
    code: ["function fib(n) {", "  if (n <= 1) return n;", "  return fib(n - 1) + fib(n - 2);", "}"],
    correctLines: [2],
    explanation: "The line with two recursive calls is what doubles the work at every level. A single recursive call would be O(n); two calls without memoization is what explodes to O(2ⁿ)." },

  // ---------- N. COMPARE (GROWTH-RATE CONTRAST) ----------
  { id: "cmp-nlogn-vs-n2", tier: 3, type: "compare",
    prompt: "For very large n, which algorithm is faster?",
    optionA: { label: "O(n log n)", curve: (n) => n * Math.log2(Math.max(n, 1)) },
    optionB: { label: "O(n\u00b2)", curve: (n) => n * n },
    answer: "A",
    explanation: "n log n grows much slower than n². At n = 1,000: n log n ≈ 10,000 but n² = 1,000,000. This is why merge sort beats bubble sort on large inputs." },
  { id: "cmp-log-vs-const", tier: 3, type: "compare",
    prompt: "For n = 1,000,000, which is faster in absolute terms?",
    optionA: { label: "O(log n)", curve: (n) => Math.log2(n) },
    optionB: { label: "O(1) with constant = 1000", curve: (n) => 1000 },
    answer: "A",
    explanation: "At n = 1,000,000: log₂(1,000,000) ≈ 20. So 20 operations beats 1000 operations. Big O describes growth, not absolute speed — but here the constant is so large that log n wins even in absolute terms." },
  { id: "cmp-log-vs-sqrt", tier: 3, type: "compare",
    prompt: "For n = 1 billion, which is faster?",
    optionA: { label: "O(log n)", curve: (n) => Math.log2(n) },
    optionB: { label: "O(\u221an)", curve: (n) => Math.sqrt(n) },
    answer: "A",
    explanation: "log₂(10⁹) ≈ 30. √(10⁹) ≈ 31,623. Logarithms crush square roots for any sizable n." },
  { id: "cmp-n-vs-nlogn", tier: 3, type: "compare",
    prompt: "For large n, which is faster?",
    optionA: { label: "O(n)", curve: (n) => n },
    optionB: { label: "O(n log n)", curve: (n) => n * Math.log2(Math.max(n, 1)) },
    answer: "A",
    explanation: "O(n) beats O(n log n) — the log factor adds real work. This is why hash-based dedup (O(n)) beats sort-then-dedup (O(n log n))." },
];
